---
title: "LessonLab7"
author: "alex dukart"
date: "2023-07-17"
output: html_document
---
gganimate!!!


```{r}
library(ggplot2)
library(gganimate)
library(gapminder)
```

```{r}
#note aes part
p <- ggplot(
  gapminder, 
  aes(x = gdpPercap, y=lifeExp, size = pop, colour = country)
  ) +
  geom_point(show.legend = FALSE, alpha = 0.7) +
  scale_color_viridis_d() +
  scale_size(range = c(2, 12)) +
  scale_x_log10() +
  labs(x = "GDP per capita", y = "Life expectancy")
p
```

```{r}
p + transition_time(year) +
  labs(title = "Year: {frame_time}")
```


```{r}
p + facet_wrap(~continent) +
  transition_time(year) +
  labs(title = "Year: {frame_time}")
```




```{r}
p + transition_time(year) +
  labs(title = "Year: {frame_time}") +
  shadow_wake(wake_length = 0.1, alpha = FALSE)
```


```{r}
p <- ggplot(
  airquality,
  aes(Day, Temp, group = Month, color = factor(Month))
  ) +
  geom_line() +
  scale_color_viridis_d() +
  labs(x = "Day of Month", y = "Temperature") +
  theme(legend.position = "top")
p
```

```{r}
p + transition_reveal(Day)
```









